# ----------------------------------------------------------------------------
# REQUIRED
# ----------------------------------------------------------------------------

title: University of New Mexico Historic Preservation & Regionalism Digital Lab
author: University of New Mexico Historic Preservation & Regionalism Program
description: Digital repository for the University of New Mexico Historic Preservation & Regionalism Program, showcasing heritage documentation, 3D models, digital reconstructions, and research projects.

url: "https://unmhpr.github.io"
baseurl: "/UNM-Historic-Preservation-Digital-Lab"

# ----------------------------------------------------------------------------
# OPTIONAL
# ----------------------------------------------------------------------------

analytics_id:
search: true

# ----------------------------------------------------------------------------
# Jekyll
# ----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
